name: Octo Organization CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Run a one-line script
        run: echo Hello from my org

  call-deployment-workflow-in-repo:
    uses: morrisseycode-testorg1/.github/.github/workflows/reusable-workflow.yml@main
